### PR TITLE
switched from notional-labs/ibc-go/v3 to cosmos/ibc-go/v3

### PR DESCRIPTION
**Pull request by oopcode**
This PR replaces a custom upgrade to ibc v3 by notional labs to the "official" upgrade by the ibc-go team (https://github.com/cosmos/ibc-go/pull/1205)

### CODE REVIEW

**Comment by faddat** [comment]
No I think that this is correct.  

I am sorry about the slow review: juno.

**Review by faddat — APPROVED** [review]
approved pending review by @catShaark

**Comment by catShaark** [comment]
I think our update now is flawed because we don't have the code to support ica for wasmd.

**Review by catShaark — APPROVED** [review]
yesss

**Comment by faddat** [comment]
@catShaark @oopcode would you guys mind having a look at branch ica-v3?

**Comment by catShaark** [comment]
I'm putting an issue to ibc-go now, I will propose that they remove `counterPartyPortID` validation in ica host recv packet logic

**Pull request merged**
